[package]
name = "music_player"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
glib = "0.20.9"
gtk4 = "0.9.6"
lazy_static = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
